#############################################################################
# Makefile for building: XJudger
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 12? 29 20:22:47 2011
# Project:  XJudger.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile XJudger.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtXml -L/usr/lib64 -L/usr/lib64/qt4 -lQtGui -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = XMLReader.cpp \
		DataInfo.cpp \
		JudgerTreeView.cpp \
		PersonInfo.cpp \
		Tree.cpp \
		JudgerProcess.cpp \
		XJudgerView.cpp \
		File.cpp \
		Time.cpp \
		main.cpp moc_XJudgerMain.cpp \
		moc_XJudgerTest.cpp \
		moc_JudgerThread.cpp \
		moc_JudgerTreeView.cpp \
		moc_XJudgerView.cpp \
		qrc_artwork.cpp
OBJECTS       = XMLReader.o \
		DataInfo.o \
		JudgerTreeView.o \
		PersonInfo.o \
		Tree.o \
		JudgerProcess.o \
		XJudgerView.o \
		File.o \
		Time.o \
		main.o \
		moc_XJudgerMain.o \
		moc_XJudgerTest.o \
		moc_JudgerThread.o \
		moc_JudgerTreeView.o \
		moc_XJudgerView.o \
		qrc_artwork.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		XJudger.pro
QMAKE_TARGET  = XJudger
DESTDIR       = 
TARGET        = XJudger

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_XJudgerMain.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: XJudger.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl
	$(QMAKE) -unix -o Makefile XJudger.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile XJudger.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/XJudger1.0.0 || $(MKDIR) .tmp/XJudger1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/XJudger1.0.0/ && $(COPY_FILE) --parents headers/File.h headers/classes.h headers/Tree.h headers/XJudgerMain.h headers/XJudgerTest.h headers/JudgerThread.h headers/XMLReader.h headers/DataInfo.h headers/JudgerTreeView.h headers/PersonInfo.h headers/JudgerProcess.h headers/XJudgerView.h headers/Time.h .tmp/XJudger1.0.0/ && $(COPY_FILE) --parents artwork/artwork.qrc .tmp/XJudger1.0.0/ && $(COPY_FILE) --parents XMLReader.cpp DataInfo.cpp JudgerTreeView.cpp PersonInfo.cpp Tree.cpp JudgerProcess.cpp XJudgerView.cpp File.cpp Time.cpp main.cpp .tmp/XJudger1.0.0/ && $(COPY_FILE) --parents XJudgerMain.ui .tmp/XJudger1.0.0/ && (cd `dirname .tmp/XJudger1.0.0` && $(TAR) XJudger1.0.0.tar XJudger1.0.0 && $(COMPRESS) XJudger1.0.0.tar) && $(MOVE) `dirname .tmp/XJudger1.0.0`/XJudger1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/XJudger1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_XJudgerMain.cpp moc_XJudgerTest.cpp moc_JudgerThread.cpp moc_JudgerTreeView.cpp moc_XJudgerView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_XJudgerMain.cpp moc_XJudgerTest.cpp moc_JudgerThread.cpp moc_JudgerTreeView.cpp moc_XJudgerView.cpp
moc_XJudgerMain.cpp: headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h \
		headers/XJudgerMain.h
	/usr/bin/moc $(DEFINES) $(INCPATH) headers/XJudgerMain.h -o moc_XJudgerMain.cpp

moc_XJudgerTest.cpp: headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h \
		headers/XJudgerTest.h
	/usr/bin/moc $(DEFINES) $(INCPATH) headers/XJudgerTest.h -o moc_XJudgerTest.cpp

moc_JudgerThread.cpp: headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h \
		headers/JudgerThread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) headers/JudgerThread.h -o moc_JudgerThread.cpp

moc_JudgerTreeView.cpp: headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h \
		headers/JudgerTreeView.h
	/usr/bin/moc $(DEFINES) $(INCPATH) headers/JudgerTreeView.h -o moc_JudgerTreeView.cpp

moc_XJudgerView.cpp: headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h \
		headers/XJudgerView.h
	/usr/bin/moc $(DEFINES) $(INCPATH) headers/XJudgerView.h -o moc_XJudgerView.cpp

compiler_rcc_make_all: qrc_artwork.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_artwork.cpp
qrc_artwork.cpp: artwork/artwork.qrc \
		artwork/Splash.xcf \
		artwork/XJudgerView.png \
		artwork/XJudgerMain.png \
		artwork/User.png \
		artwork/XJudgerTest.png \
		artwork/TestCaseExpand.png \
		artwork/TestCase.png
	/usr/bin/rcc -name artwork artwork/artwork.qrc -o qrc_artwork.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_XJudgerMain.h
compiler_uic_clean:
	-$(DEL_FILE) ui_XJudgerMain.h
ui_XJudgerMain.h: XJudgerMain.ui
	/usr/bin/uic XJudgerMain.ui -o ui_XJudgerMain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

XMLReader.o: XMLReader.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XMLReader.o XMLReader.cpp

DataInfo.o: DataInfo.cpp headers/DataInfo.h \
		headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataInfo.o DataInfo.cpp

JudgerTreeView.o: JudgerTreeView.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JudgerTreeView.o JudgerTreeView.cpp

PersonInfo.o: PersonInfo.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PersonInfo.o PersonInfo.cpp

Tree.o: Tree.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tree.o Tree.cpp

JudgerProcess.o: JudgerProcess.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JudgerProcess.o JudgerProcess.cpp

XJudgerView.o: XJudgerView.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XJudgerView.o XJudgerView.cpp

File.o: File.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o File.o File.cpp

Time.o: Time.cpp headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Time.o Time.cpp

main.o: main.cpp JudgerThread.cpp \
		headers/classes.h \
		headers/Tree.h \
		headers/Time.h \
		headers/XMLReader.h \
		headers/XJudgerView.h \
		headers/XJudgerMain.h \
		headers/JudgerProcess.h \
		headers/JudgerThread.h \
		headers/XJudgerTest.h \
		headers/DataInfo.h \
		headers/JudgerTreeView.h \
		headers/PersonInfo.h \
		headers/File.h \
		XJudgerTest.cpp \
		XJudgerMain.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_XJudgerMain.o: moc_XJudgerMain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_XJudgerMain.o moc_XJudgerMain.cpp

moc_XJudgerTest.o: moc_XJudgerTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_XJudgerTest.o moc_XJudgerTest.cpp

moc_JudgerThread.o: moc_JudgerThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_JudgerThread.o moc_JudgerThread.cpp

moc_JudgerTreeView.o: moc_JudgerTreeView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_JudgerTreeView.o moc_JudgerTreeView.cpp

moc_XJudgerView.o: moc_XJudgerView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_XJudgerView.o moc_XJudgerView.cpp

qrc_artwork.o: qrc_artwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_artwork.o qrc_artwork.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

